<a href="https://colab.research.google.com/github/Barbara-Morais/Exercicios-Bootcamp/blob/main/Exerc%C3%ADcios_Classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [ ]:
#Load dataset
wine = datasets.load_wine()
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
df_data = pd.DataFrame(data= np.c_[wine['data'], wine['target']],
                     columns= wine['feature_names'] + ['target'])

In [ ]:
df_data

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43  ...                          3.92   1065.0     0.0
1      13.20        1.78  2.14  ...                          3.40   1050.0     0.0
2      13.16        2.36  2.67  ...                          3.17   1185.0     0.0
3      14.37        1.95  2.50  ...                          3.45   1480.0     0.0
4      13.24        2.59  2.87  ...                          2.93    735.0     0.0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0     2.0
174    13.40        3.91  2.48  ...                          1.56    750.0     2.0
175    13.27        4.28  2.26  ...                          1.56    835.0     2.0
176    13.17        2.59  2.37  ...                          1.62    840.0     2.0
177    14.13        4.10  2.74  ...                          1.60    560.0     2.0

[178 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2,random_state=3)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

Sendo o valor original do knn = 3, começo aumentando para 4

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [ ]:
y_pred = knn.predict(X_test)
y_pred

array([0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       0, 2, 0, 1, 0, 0, 1, 2, 1, 0, 2, 1, 1, 2])

In [ ]:
from sklearn.metrics import r2_score
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9444444444444444


Aumentando para 5

In [ ]:
knn5 = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred5 = knn5.predict(X_test)
y_pred5

array([0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       0, 2, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 1, 2])

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred5))

Accuracy: 0.9166666666666666


Aumentando para 6

In [ ]:
knn6 = KNeighborsClassifier(n_neighbors=6)

In [ ]:
knn6.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [ ]:
y_pred6 = knn6.predict(X_test)
y_pred6

array([0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       0, 2, 0, 1, 0, 0, 1, 2, 1, 0, 2, 1, 1, 2])

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred6))

Accuracy: 0.9444444444444444


knn = 7

In [ ]:
knn7 = KNeighborsClassifier(n_neighbors=7)

In [ ]:
knn7.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [ ]:
y_pred7 = knn7.predict(X_test)
y_pred7

array([0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       0, 2, 0, 1, 0, 0, 1, 2, 1, 0, 2, 1, 1, 2])

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred7))

Accuracy: 0.9444444444444444


knn = 8

In [ ]:
knn8 = KNeighborsClassifier(n_neighbors=8)

In [ ]:
knn8.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [ ]:
y_pred8 = knn8.predict(X_test)
y_pred8

array([0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       0, 2, 0, 1, 0, 0, 1, 2, 1, 0, 2, 1, 1, 2])

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred8))

Accuracy: 0.9444444444444444
